version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: tests
          command: npm test
